services:
  basic-server:
    image: kotlin-spring-starter
    container_name: basic-server
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      APP: ./build/libs/kotlin-spring-starter-0.0.1-SNAPSHOT.jar